import React from "react";
import { useNavigate, BrowserRouter } from 'react-router-dom';
import Router from 'next/router'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Role: NextPage = () => {

  const begin = () => {
    Router.push('/mint')
  }

  const back = () => {
    Router.push('/choose_role')
  }

  return (
      <div className={styles.container}>
        <Head>
          <title>Soulbound Tokens Playground</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <a>Here you can issue certificates to Cannabis Businesses.</a>
          <br />
          <button onClick={begin}>
            Simulate Parsl Token Issuance
          </button>
          <br />
          <button onClick={back}>
            Go Back
          </button>
        </main>

      </div>
  )
}

export default Role