import React from "react";
import Router from 'next/router'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Role: NextPage = () => {

  const begin = () => {
    Router.push('/mint')
  }

  const revoke = () => {
    Router.push('/revoke')
  }

  const back = () => {
    Router.push('/choose_role')
  }

  return (
      <div className={styles.container}>
        <Head>
          <title>Soulbound Tokens Playground</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h3>Here you can issue certificates to Cannabis Businesses.</h3>
          <br />
          <button className={styles.button} onClick={begin}>
            Simulate Parsl Token Issuance
          </button>
          <br />
          <h4>You can also revoke them if required.</h4>
          <br />
          <button className={styles.button} onClick={revoke}>
            Simulate Parsl Token Revoking
          </button>
          <br />
          <br />
          <br />
          <button className={styles.goBackButton} onClick={back}>
            Go Back
          </button>
        </main>

      </div>
  )
}

export default Role